package com.p2pdinner.exceptions;

public enum Reason {
	UNKNOWN, 
	ZERO_RESULTS, 
	BAD_REQUEST, 
	INTERNAL_SERVER_ERROR, 
	INSUFFICIENT_QUANTITY, 
	FAILED_TO_PLACE_ORDER, 
	ORDER_NOT_READY, 
	NO_PAYMENT_INFORMATION,
	INVALID_MENU_ITEM
}
