package com.p2pdinner.domain;

public enum OrderStatus {
	ORDER_IN_PROGRESS, READY_TO_PROCESS, PROCESSING, RECEIVED, DELIVERED, EXPIRED, PROCESSING_ERROR, UNKNOWN_ERROR, REFUND, MISSING_PAYMENT_INFORMATION
}
